export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE';

export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOADED = "AUTH_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_USERS = 'GET_USERS';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_LOADER = "USER_LOADER";

export const GET_AREA_PRICES = 'GET_AREA_PRICES';
export const ADD_AREA_PRICE = 'ADD_AREA_PRICE';
export const UPDATE_AREA_PRICE = 'UPDATE_AREA_PRICE';
export const DELETE_AREA_PRICE = 'DELETE_AREA_PRICE';
export const AREA_PRICE_LOADER = 'AREA_PRICE_LOADER';

export const GET_DISPATCH_CONTROL_MESSENGERS = 'GET_DISPATCH_CONTROL_MESSENGERS';
export const ADD_DISPATCH_CONTROL_MESSENGER = 'ADD_DISPATCH_CONTROL_MESSENGER';          
export const UPDATE_DISPATCH_CONTROL_MESSENGER = 'UPDATE_DISPATCH_CONTROL_MESSENGER';
export const DELETE_DISPATCH_CONTROL_MESSENGER = 'DELETE_DISPATCH_CONTROL_MESSENGER';
export const DISPATCH_CONTROL_MESSENGER_LOADER = 'DISPATCH_CONTROL_MESSENGER_LOADER';

export const GET_BARCODE_MIDDLE_TEXT = 'GET_BARCODE_MIDDLE_TEXT';
export const ADD_BARCODE_MIDDLE_TEXT = 'ADD_BARCODE_MIDDLE_TEXT';
export const UPDATE_BARCODE_MIDDLE_TEXT = 'UPDATE_BARCODE_MIDDLE_TEXT';
export const DELETE_BARCODE_MIDDLE_TEXT = 'DELETE_BARCODE_MIDDLE_TEXT';
export const BARCODE_MIDDLE_TEXT_LOADER = 'BARCODE_MIDDLE_TEXT_LOADER';

export const GET_ENCODE_LIST = 'GET_ENCODE_LIST';
export const ADD_ENCODE_LIST = 'ADD_ENCODE_LIST';
export const DELETE_ENCODE_LIST = 'DELETE_ENCODE_LIST';
export const UPDATE_ENCODE_LIST = 'UPDATE_ENCODE_LIST';
export const ENCODE_LIST_LOADER = "ENCODE_LIST_LOADER";

export const GET_RECORD = 'GET_RECORD';
export const ADD_RECORD = 'ADD_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const RECORD_LOADER = "RECORD_LOADER";

export const TOP_ALERT = 'TOP_ALERT';
export const MODAL_TOP_ALERT = 'MODAL_TOP_ALERT';
export const SECOND_MODAL_TOP_ALERT = 'SECOND_MODAL_TOP_ALERT';

export const GET_ENCODE_LIST_COUNT = 'GET_ENCODE_LIST_COUNT';
export const ADD_ENCODE_LIST_COUNT = 'ADD_ENCODE_LIST_COUNT';
export const DELETE_ENCODE_LIST_COUNT = 'DELETE_ENCODE_LIST_COUNT';
export const ENCODE_LIST_COUNT_LOADER = 'ENCODE_LIST_COUNT_LOADER';

export const ADD_DASHBOARD_COUNT = 'ADD_DASHBOARD_COUNT';
export const DELETE_DASHBOARD_COUNT = 'DELETE_DASHBOARD_COUNT';
export const DASHBOARD_COUNT_LOADER = 'DASHBOARD_COUNT_LOADER';
export const GET_DASHBOARD_COUNT = 'GET_DASHBOARD_COUNT';